services:
  - type: web
    name: student-management-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      # Add other environment variables from your .env file here
      - key: MONGO_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

  - type: web
    name: student-management-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 10001
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://student-management-backend.onrender.com

databases:
  - name: mongodb
    databaseName: SMS
    user: durgaprasad10451718
    plan: free
