const express = require('express');
const router = express.Router();
const reportController = require('../controllers/reportController');
const auth = require('../middleware/auth');

// Generate a PDF report for a student
router.post('/student', auth(['admin', 'student']), reportController.generateStudentReport);
router.post('/student/:studentId', auth(['admin', 'student']), reportController.generateStudentReport);
router.get('/student', auth(['admin', 'student']), reportController.generateStudentReport);
router.get('/student/:studentId', auth(['admin', 'student']), reportController.generateStudentReport);
router.get('/class', auth(['admin']), reportController.generateClassReport);
// Admin: Get all reports
router.get('/', auth('admin'), reportController.getAllReports);
// Admin: Download report (PDF or CSV)
router.get('/:id/download', auth('admin'), reportController.downloadReport);
router.delete('/:id', auth('admin'), reportController.deleteReport);
// Bulk delete reports (use POST for better compatibility)
router.post('/bulk-delete', auth('admin'), reportController.bulkDeleteReports);
// Student: Get their own reports
router.get('/my', auth(['student']), reportController.getMyReports);
// Student: Get reports generated by themselves
router.get('/generated-by-me', auth(['student']), reportController.getReportsGeneratedByMe);
// Student: Download a report they generated (PDF, CSV, XLSX)
router.get('/my/:id/download', auth(['student']), reportController.downloadReport);
// Student: Delete a report by ID (must be generated by them)
router.delete('/my/:id', auth(['student']), reportController.deleteMyReport);
// Student: Bulk delete reports (must be generated by them)
router.post('/my/bulk-delete', auth(['student']), reportController.bulkDeleteMyReports);

module.exports = router;
